services:
    mizolab_backend:
        build:
            context: ./src/vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src:/var/www/html'
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
            minio:
                condition: service_started
            ftpd:
                condition: service_started
    # DBサーバ
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: 'mizo'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 10s

    # ストレージサーバ（仮想S3）
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: 'sail'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - 'sail-minio:/data/minio'
        networks:
            - sail
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s
    # ストレージサーバ（FTP）
    # Ref: https://github.com/stilliard/docker-pure-ftpd/blob/master/docker-compose.yml
    ftpd:
        image: stilliard/pure-ftpd
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        environment:
            PUBLICHOST: '${FTP_HOST}'
            FTP_USER_NAME: '${FTP_USER_NAME}'
            FTP_USER_PASS: '${FTP_PASSWORD}'
            FTP_USER_HOME: /home/ftpusers/username
        volumes:
            - "sail-ftpd:/home/username/"
            - "sail-ftpd:/etc/pure-ftpd/passwd"
        networks:
            - sail
    selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-minio:
        driver: local
    sail-ftpd:
        driver: local
